// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockDataStore is an autogenerated mock type for the DataStore type
type MockDataStore struct {
	mock.Mock
}

// Store provides a mock function with given fields: _a0
func (_m *MockDataStore) Store(_a0 *Info) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Info) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockDataStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDataStore creates a new instance of MockDataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDataStore(t mockConstructorTestingTNewMockDataStore) *MockDataStore {
	mock := &MockDataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
